// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:51817' | (string & {});
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];
